@startuml
start
:User inputs a command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:LogicManager executes the user command
and returns an instance of CommandResult;

if () then ([commandResult.shouldDisplayClient()])
    :Remove all child components in
    the Display Panel Container;
    :Add the Container of the
    Client View UI as a child component
    of the Display Panel Container;
else ([else])
  if () then ([commandResult.shouldDisplayCountryNote()])
      :Remove all child components in
      the Display Panel Container;
      :Add the Container of the
      Country Note Panel UI as a child component
      of the Display Panel Container;
  else ([else])
  endif
endif
stop
@enduml
