@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MainParser" as MainParser LOGIC_COLOR
participant "c : CountryNoteAddCommand" as CountryNoteAddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(country note add)
activate LogicManager

LogicManager -> MainParser : parseCommand(country note add)
activate MainParser

create CountryNoteAddCommand
MainParser -> CountryNoteAddCommand
activate CountryNoteAddCommand

CountryNoteAddCommand --> MainParser
deactivate CountryNoteAddCommand

MainParser --> LogicManager : c
deactivate MainParser

LogicManager -> CountryNoteAddCommand : execute()
activate CountryNoteAddCommand

CountryNoteAddCommand -> Model : addCountryNote(countryNote)
activate Model

Model --> CountryNoteAddCommand
deactivate Model

CountryNoteAddCommand --> LogicManager : result
deactivate CountryNoteAddCommand
CountryNoteAddCommand -[hidden]-> LogicManager : result
destroy CountryNoteAddCommand

[<--LogicManager
deactivate LogicManager
@enduml
