@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Country
Class CountryNotesManager
Class CountryCodeVerifier
Class Note
Class CountryNote
Class AddressBook

CountryNote -up-|> Note
CountryNote -r-> "1" Country
CountryNotesManager "1" -up-> "*" CountryNote
Country .up.> CountryCodeVerifier
AddressBook -left-> "1" CountryNotesManager

@enduml
