@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MainParser" as MainParser LOGIC_COLOR
participant ":ClientDeleteCommandParser" as ClientDeleteCommandParser LOGIC_COLOR
participant "d:ClientDeleteCommand" as ClientDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("client delete 1")
activate LogicManager

LogicManager -> MainParser : parseCommand("client delete 1")
activate MainParser

create ClientDeleteCommandParser
MainParser -> ClientDeleteCommandParser
activate ClientDeleteCommandParser

ClientDeleteCommandParser --> MainParser
deactivate ClientDeleteCommandParser

MainParser -> ClientDeleteCommandParser : parse("1")
activate ClientDeleteCommandParser

create ClientDeleteCommand
ClientDeleteCommandParser -> ClientDeleteCommand
activate ClientDeleteCommand

ClientDeleteCommand --> ClientDeleteCommandParser : d
deactivate ClientDeleteCommand

ClientDeleteCommandParser --> MainParser : d
deactivate ClientDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ClientDeleteCommandParser -[hidden]-> MainParser
destroy ClientDeleteCommandParser

MainParser --> LogicManager : d
deactivate MainParser

LogicManager -> ClientDeleteCommand : execute()
activate ClientDeleteCommand

ClientDeleteCommand -> Model : deleteClient(1)
activate Model

Model --> ClientDeleteCommand
deactivate Model

create CommandResult
ClientDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> ClientDeleteCommand
deactivate CommandResult

ClientDeleteCommand --> LogicManager : result
deactivate ClientDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
